repos:
#- repo: https://github.com/rstcheck/rstcheck
#  rev: v6.2.4  # Use the sha / tag you want to point at   
#  hooks:
#  - id: rstcheck
#    additional_dependencies: [sphinx]
#    exclude: source/res
#    args: [--report-level=info, --config=.rstcheck.project.cfg]

# ----------------------------------------------
# Validate .pre-commit-hooks.yaml file
# ----------------------------------------------
- repo: https://github.com/pre-commit/pre-commit
  rev: v3.7.1
  hooks:
  - id: validate_manifest
